### 결제 요청 생성
POST localhost:8080/api/payment-requests
Content-Type: application/json

{
  "merchantId": "11ee982bb369b970aa864daaa5a26fcc",
  "amount": 10000
}

> {%
  client.global.set("requestId", response.body.requestId);
%}

### 결제 요청 조회
GET localhost:8080/api/payment-requests/{{requestId}}

### 결제
POST localhost:8080/api/payments
Content-Type: application/json

{
  "requestId": "{{requestId}}",
  "merchantId": "11ee982bb369b970aa864daaa5a26fcc",
  "amount": 9000,
  "tax": 1000,
  "userId": "11ee982bf1f254c091f76b4ba6b082a2"
}
